### ISSUE TITLE
Add top-level Readme

### ISSUE THREAD

**Issue by sbesson** [CellMigStandOrg/CMSO-training#4]
Possible content:

- short description of the intent of this repository
- dev section: builing and running the Docker image
- (if possible) link to a resource like https://mybinder.org allowing to execute the notebook interactively

**Comment by agbeltran** [comment]
Thanks, @sbesson for adding this issue!
We should also add a link to the primary repository of the dataset (https://github.com/CellMigStandOrg/CMSO-datasets/tree/master/cmsodataset0001-masuzzo).
In my experience, if we use  https://mybinder.org, then we should remove the Dockerfile.
